apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: harbor.local.lab/library/myapp
    newName: harbor.local.lab/library/myapp
    newTag: "275"

commonLabels:
  app: boardgame
  managed-by: argocd

