apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base/boardgame

images:
- name: harbor.local.lab/library/boardgame
  newTag: "313"

